language: node_js

compiler: gcc
sudo: false

os:
- linux
#- osx

env:
  global:
    - secure: pDjeE1LVOY2efDaIqyfOeLisCyHN3PXuWak+ubsjC2/IH0rMzQ5ftvfaAi2mfx/emtA7EhCajB4X070EncnSjlfcgNRUsDDw5HJ75BucG+oiFKN3nS5DiLL45cRcYlMM2OwF/FniEo70KgnaN0JjpaWmWAybx9oR6n5JBbB5YKp9tXzWLeaxrs3TqpuPWU+/dhAaAsMAiHKGqKj8sWIVLVS9lgXE6GQodC8RfHOcXUOafZelH4cBztRGyPJ9cX1/w/gjtP5sVScIrhJJfnDHFYXX5FfhZtveLncnc1/+ZrXt/Px/NG8FfkYmdrQuQfY8isFVnucsH9GjN9ezPbaJxizaIyB0b0wOCZjpQL3hAJPbUYTlNPU4Fls+QXPyW6Y75rNq8SHKwoTNLaiwGYZI1GkZj4x7P/ODmDxUt5X8KnwvjnSxgiMUX99NnUbXDPiLwIFS7PfE4gMI0XHqpW4cX14bMY3RB26vCMvIyOZXa0u6Pw0RjFcoK+nT8bM6e89klqloobURFqfZvJ5tvYmlICYFlx3y7+baOpfoJ/NNY2QnSxVrBedNyZ3ngpGoEzOoKryNAMW/+VMgNf+fAgk080t3G+lQ1T+QjKC4bSxQ0GmxkLjenMINN/g2lZwQecfChNKtGsfiHknZ9BVbpDfrytAC3eAfsVvWfXRiMci8iyw=

node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    
sudo: false

before_install:
- if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CC="gcc-4.8";
    export CXX="g++-4.8";
    export LINK="gcc-4.8";
    export LINKXX="g++-4.8";
  fi
- nvm --version
- node --version
- npm --version
- gcc --version
- g++ --version

before_script:
# figure out if we should publish
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`
- PUBLISH_BINARY=false
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` || ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then PUBLISH_BINARY=true; fi;
- echo "Publishing binaries? ->" $PUBLISH_BINARY

install:
- npm install

script:
- npm test
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package && node-pre-gyp-github publish --release; fi;

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules