language: node_js

compiler: gcc
sudo: false

os:
- osx

env:
- CXX=g++-4.9

node_js:
- '8'

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - g++-4.9
    - clang-3.7
    
sudo: false

before_install:
- if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;
- if [ $TRAVIS_OS_NAME == "osx" ]; then export CXX=clang++; fi
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CC="gcc-4.9";
    export CXX="g++-4.9";
    export LINK="gcc-4.9";
    export LINKXX="g++-4.9";
  fi
- nvm --version
- node --version
- npm --version
- g++ --version
- clang --version
- npm config set progress false
- npm config set spin false

before_script:
# figure out if we should publish
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`
- PUBLISH_BINARY=false
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` || ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then PUBLISH_BINARY=true; fi;
- echo "Publishing binaries? ->" $PUBLISH_BINARY

install:
- npm install

script:
- npm test
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package && node-pre-gyp-github publish --release; fi;

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules